export const LOGIN = "LOGIN";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGOUT = "LOGOUT";

export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_FASKES = "GET_LOCATION_FASKES";
export const GET_LOCATION_BY_ID = "GET_LOCATION_BY_ID";
export const GET_KELURAHAN = "GET_KELURAHAN";
export const GET_KELURAHAN_BY_ID = "GET_KELUIRAHAN_BY_ID";
export const GET_FASKES = "GET_FASKES";
export const GET_FASKES_BY_ID = "GET_FASKES_BY_ID";

export const GET_PASIEN = "GET_PASIEN";
export const GET_PASIEN_BY_ID = "GET_PASIEN_BY_ID";
export const GET_PASIEN_BY_ID_KEL = "GET_PASIEN_BY_ID_KEL";
export const FILTER_PASIEN = "FILTER_PASIEN";

export const GET_TAHUN = "GET_TAHUN";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const GET_ALL_USER = "GET_ALL_USER";
export const CREATE_USER = "CREATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const REAL_DATA = "REAL_DATA";
export const PREDICTED_DATA = "PREDICTED_DATA";
export const GET_KERENTANAN = "GET_KERENTANAN";
export const KERENTANAN = "KERENTANAN";
export const INTERVENSI = "INTERVENSI";

export const CREATE_PENILAIAN = "CREATE_PENILAIAN";
export const UPDATE_PENILAIAN_PUSK = "UPDATE_PENILAIAN_PUSK";
export const GET_PENILAIAN_PUSK = "GET_PENILAIAN_PUSK";
export const DELETE_PENILAIAN_PUSK = "DELETE_PENILAIAN_PUSK";
